#!/usr/bin/env python3
# Score one mission's defects.json against its site ground truth
import argparse
import json
import math
import os

import yaml

CAMERA_RATE_HZ = 15
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_PARAMS_FILE = os.path.join(REPO_ROOT, 'src', 'kestrel', 'config', 'kestrel_params.yaml')

BENCHMARKS_HEADER = """# Kestrel benchmarks

Measured numbers from real mission runs, generated by `scripts/score_mission.py`.
Detection rate is defects found over ground truth marker count, localization
error is the distance from each detected defect to its nearest ground truth
marker, photos versus frames streamed shows how much of the raw camera feed
makes it from a mission into the report.

| Site | Timestamp | Detection rate | Mean error (m) | Max error (m) | Duration (s) | Photos vs frames streamed |
|---|---|---|---|---|---|---|
"""


# Read the ground_truth marker positions from a params yaml, label to xyz
def read_ground_truth(yaml_path):
    with open(yaml_path) as yaml_file:
        data = yaml.safe_load(yaml_file)

    ground_truth_block = data.get('ground_truth', {}).get('ros__parameters', {})
    ground_truth = {}
    for key, position in ground_truth_block.items():
        if key.endswith('_position'):
            label = key[:-len('_position')]
            ground_truth[label] = position

    return ground_truth


# Straight line distance between two north east altitude points
def distance_meters(point_a, point_b):
    return math.sqrt(
        (point_a[0] - point_b[0]) ** 2
        + (point_a[1] - point_b[1]) ** 2
        + (point_a[2] - point_b[2]) ** 2)


# Score one mission's defects against ground truth and return the metrics
def score_mission(defects_record, ground_truth):
    ground_truth_positions = list(ground_truth.values())
    defects = defects_record['defects']

    detection_rate = len(defects) / len(ground_truth_positions) if ground_truth_positions else 0.0

    errors = []
    for defect in defects:
        defect_position = (defect['north'], defect['east'], defect['altitude'])
        nearest_distance = min(
            distance_meters(defect_position, ground_truth_position)
            for ground_truth_position in ground_truth_positions)
        errors.append(nearest_distance)

    mean_error = sum(errors) / len(errors) if errors else 0.0
    max_error = max(errors) if errors else 0.0

    duration_seconds = defects_record['duration_seconds']
    frames_streamed = duration_seconds * CAMERA_RATE_HZ

    return {
        'site': defects_record['site'],
        'timestamp': defects_record['timestamp'],
        'detection_rate': detection_rate,
        'defects_found': len(defects),
        'ground_truth_count': len(ground_truth_positions),
        'mean_error': mean_error,
        'max_error': max_error,
        'duration_seconds': duration_seconds,
        'photos': len(defects),
        'frames_streamed': frames_streamed,
    }


# Format one scored mission as a markdown table row
def format_row(scored):
    detection_text = f"{scored['defects_found']}/{scored['ground_truth_count']}"
    photos_text = f"{scored['photos']} vs {scored['frames_streamed']:.0f}"
    return (
        f"| {scored['site']} | {scored['timestamp']} | {detection_text} | "
        f"{scored['mean_error']:.2f} | {scored['max_error']:.2f} | "
        f"{scored['duration_seconds']:.1f} | {photos_text} |")


# Read the existing benchmarks table, keyed by site and timestamp
def read_existing_rows(out_path):
    if not os.path.isfile(out_path):
        return {}

    rows = {}
    with open(out_path) as out_file:
        for line in out_file:
            if not line.startswith('| ') or line.startswith('| Site') or line.startswith('|---'):
                continue
            columns = [column.strip() for column in line.strip('|\n').split('|')]
            site, timestamp = columns[0], columns[1]
            rows[(site, timestamp)] = line.rstrip('\n')

    return rows


# Write the header and every row, sorted by site then timestamp
def write_benchmarks(out_path, rows):
    with open(out_path, 'w') as out_file:
        out_file.write(BENCHMARKS_HEADER)
        for key in sorted(rows):
            out_file.write(rows[key] + '\n')


# Parse arguments, score the mission, and update the benchmarks file
def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', required=True, help='Path to a reports/<timestamp> directory')
    parser.add_argument('--site-config', required=True, help='Path to the site overlay yaml')
    parser.add_argument('--out', default='docs/benchmarks.md', help='Benchmarks markdown file to update')
    arguments = parser.parse_args()

    with open(os.path.join(arguments.report, 'defects.json')) as defects_file:
        defects_record = json.load(defects_file)

    ground_truth = read_ground_truth(arguments.site_config)
    if not ground_truth:
        ground_truth = read_ground_truth(BASE_PARAMS_FILE)

    scored = score_mission(defects_record, ground_truth)

    rows = read_existing_rows(arguments.out)
    rows[(scored['site'], scored['timestamp'])] = format_row(scored)
    write_benchmarks(arguments.out, rows)

    print(f"scored {scored['site']} {scored['timestamp']}: "
          f"{scored['defects_found']}/{scored['ground_truth_count']} found, "
          f"mean error {scored['mean_error']:.2f} m")


if __name__ == '__main__':
    main()
